FROM ubuntu:20.04
MAINTAINER Andrey Fedoseev <andrey@andreyfedoseev.com>
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y autoconf libtool npm wget
RUN ln -s /usr/bin/nodejs /usr/local/bin/node
RUN npm install -g coffeescript@2.7.0
RUN npm install -g livescript@1.6.0
RUN npm install -g less@4.1.3
RUN npm install -g babel-cli@6.26.0
RUN npm install -g stylus@0.50.0
RUN npm install -g handlebars@4.7.7
RUN wget -O /tmp/dart-sass.tar.gz https://github.com/sass/dart-sass/releases/download/1.66.0/dart-sass-1.66.0-linux-x64.tar.gz && \
    tar -xzf /tmp/dart-sass.tar.gz -C /opt && \
    rm -rf /tmp/dart-sass.tar.gz
ENV PATH="/opt/dart-sass:${PATH}"
